server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: app-verify

  datasource:
    url: jdbc:mysql://150.158.14.9:3306/app_verify?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Root@123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 可以是 none, validate, update, create, create-drop
    show-sql: true       # 控制台打印 SQL
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect  # 根据 MySQL 版本调整

# 可选：设置全局日志级别
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
